# Generated by Django 4.2 on 2024-06-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('name', models.CharField(max_length=200, unique=True)),
                ('repo_url', models.CharField(max_length=1000)),
                ('repo_path', models.CharField(max_length=1000)),
                ('repo_branch', models.CharField(default='master', max_length=100)),
                ('last_stat_commit', models.CharField(default=None, max_length=50, null=True)),
                ('last_sync_at', models.DateTimeField(default=None, null=True)),
                ('status', models.CharField(default='inactive', max_length=10)),
                ('active_days', models.IntegerField(default=0)),
                ('files_count', models.IntegerField(default=0)),
                ('commits_count', models.IntegerField(default=0)),
                ('first_commit_id', models.CharField(default='', max_length=50)),
                ('last_commit_id', models.CharField(default='', max_length=50)),
                ('first_commit_at', models.DateTimeField(default=None, null=True)),
                ('last_commit_at', models.DateTimeField(default=None, null=True)),
                ('age', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
