# Generated by Django 4.2 on 2024-06-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('repo_url', models.CharField(max_length=1000)),
                ('repo_path', models.CharField(max_length=1000)),
                ('branch', models.CharField(default='master', max_length=100)),
                ('head_commit', models.CharField(default=None, max_length=50, null=True)),
                ('last_stat_commit', models.CharField(default=None, max_length=50, null=True)),
                ('last_sync_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
