# Generated by Django 4.2 on 2024-06-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='branch',
            new_name='repo_branch',
        ),
    ]
