# Generated by Django 4.2 on 2024-06-17 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_branch_project_repo_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='head_commit',
        ),
        migrations.AddField(
            model_name='project',
            name='active_days_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='commits_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='files_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='first_commit_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='first_commit_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='last_commit_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_commit_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='last_sync_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
