# Generated by Django 4.2 on 2024-07-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectactiviy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectactiviy',
            name='author_datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='projectactiviy',
            name='author_email',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='projectactiviy',
            constraint=models.UniqueConstraint(fields=('project', 'commit_sha'), name='unique_proj_commit'),
        ),
    ]
