# Generated by Django 4.2 on 2024-06-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectlanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active_days_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃')], default='inactive', max_length=10),
        ),
    ]
