# Generated by Django 4.2 on 2024-06-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_head_commit_project_active_days_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='active_days_count',
            new_name='active_days',
        ),
    ]
