# Generated by Django 4.2 on 2024-06-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_active_days_ratio_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sync_status',
            field=models.CharField(choices=[('init', '初始化中'), ('success', '同步完成'), ('error', '同步失败')], default='init', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo_path',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
