# Generated by Django 4.2 on 2024-07-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectactiviy_author_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactiviy',
            name='commit_message',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
