# Generated by Django 4.2 on 2024-06-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_sync_status_alter_project_repo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃')], default='inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='sync_status',
            field=models.CharField(choices=[('init', '初始化'), ('conn_success', '连接成功'), ('conn_error', '连接失败'), ('stating', '数据计算中'), ('stat_success', '数据计算完成'), ('stat_error', '数据计算失败')], default='init', max_length=20),
        ),
    ]
