# Generated by Django 4.2 on 2024-08-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectactiviy_deletions_projectactiviy_insertions'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='project',
            name='sync_log',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
