# Generated by Django 4.2 on 2024-06-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_status_alter_project_sync_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sync_status',
            field=models.CharField(choices=[('init', '初始化'), ('conn_success', '连接成功'), ('conn_error', '连接失败'), ('stating', '统计中'), ('stat_success', '统计完成'), ('stat_error', '统计失败')], default='init', max_length=20),
        ),
    ]
