# Generated by Django 4.2 on 2024-08-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_desc_project_sync_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactiviy',
            name='corrected_deletions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectactiviy',
            name='corrected_insertions',
            field=models.IntegerField(default=0),
        ),
    ]
