# Generated by Django 4.2 on 2024-08-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20240819_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIgnoreList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='ignore_list',
            field=models.TextField(default=''),
        ),
    ]
