# Generated by Django 4.2 on 2024-09-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectignorelist_project_ignore_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='active_days_ratio',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='files_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo_url',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='sync_status',
            field=models.CharField(choices=[('init', '初始化'), ('conn_success', '连接成功'), ('conn_error', '连接失败'), ('stating', '统计中'), ('stat_success', '统计完成'), ('stat_error', '统计失败')], db_index=True, default='init', max_length=20),
        ),
    ]
