# Generated by Django 4.2 on 2024-10-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_active_days_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectactiviy',
            name='commit_message',
            field=models.TextField(default=''),
        ),
    ]
