# Generated by Django 4.2 on 2024-11-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_projectactiviy_commit_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='sync_log',
            new_name='error_log',
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('stating', '统计中'), ('stat_success', '统计完成'), ('stat_error', '统计失败')], db_index=True, default='stating', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='sync_status',
            field=models.CharField(choices=[('init', '初始化'), ('conn_success', '连接成功'), ('conn_error', '连接失败')], db_index=True, default='init', max_length=20),
        ),
    ]
