# Generated by Django 4.2 on 2024-11-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_rename_sync_log_project_error_log_project_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectActiviy',
            new_name='ProjectActivity',
        ),
    ]
