# Generated by Django 4.2 on 2024-12-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_rename_projectactiviy_projectactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('stating', 'Processing'), ('stat_success', 'Stat Success'), ('stat_error', 'Stat Failed')], db_index=True, default='stating', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='sync_status',
            field=models.CharField(choices=[('init', 'Init'), ('conn_success', 'Conn. OK'), ('conn_error', 'Conn. Error')], db_index=True, default='init', max_length=20),
        ),
    ]
