# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license/license.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15license/license.proto\x12\x07license\"\x07\n\x05\x45mpty\"c\n\x0bLicenseData\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x14\n\x0cmax_projects\x18\x02 \x01(\x05\x12\x17\n\x0f\x65xpiration_date\x18\x03 \x01(\t\x12\x17\n\x0flicense_version\x18\x04 \x01(\t\"\x17\n\x04Pong\x12\x0f\n\x07message\x18\x01 \x01(\t2o\n\x0eLicenseService\x12\x36\n\x0eGetLicenseData\x12\x0e.license.Empty\x1a\x14.license.LicenseData\x12%\n\x04Ping\x12\x0e.license.Empty\x1a\r.license.PongB\x1cZ\x1a\x62\x65\x61tsight-core/api/licenseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'license.license_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032beatsight-core/api/license'
  _globals['_EMPTY']._serialized_start=34
  _globals['_EMPTY']._serialized_end=41
  _globals['_LICENSEDATA']._serialized_start=43
  _globals['_LICENSEDATA']._serialized_end=142
  _globals['_PONG']._serialized_start=144
  _globals['_PONG']._serialized_end=167
  _globals['_LICENSESERVICE']._serialized_start=169
  _globals['_LICENSESERVICE']._serialized_end=280
# @@protoc_insertion_point(module_scope)
