# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import license_pb2 as license_dot_license__pb2


class LicenseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLicenseData = channel.unary_unary(
                '/license.LicenseService/GetLicenseData',
                request_serializer=license_dot_license__pb2.Empty.SerializeToString,
                response_deserializer=license_dot_license__pb2.LicenseData.FromString,
                )
        self.Ping = channel.unary_unary(
                '/license.LicenseService/Ping',
                request_serializer=license_dot_license__pb2.Empty.SerializeToString,
                response_deserializer=license_dot_license__pb2.Pong.FromString,
                )


class LicenseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLicenseData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LicenseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLicenseData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLicenseData,
                    request_deserializer=license_dot_license__pb2.Empty.FromString,
                    response_serializer=license_dot_license__pb2.LicenseData.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=license_dot_license__pb2.Empty.FromString,
                    response_serializer=license_dot_license__pb2.Pong.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'license.LicenseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LicenseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLicenseData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/license.LicenseService/GetLicenseData',
            license_dot_license__pb2.Empty.SerializeToString,
            license_dot_license__pb2.LicenseData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/license.LicenseService/Ping',
            license_dot_license__pb2.Empty.SerializeToString,
            license_dot_license__pb2.Pong.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
