# Generated by Django 4.2 on 2024-06-29 02:49

from django.db import migrations
from django.contrib.auth.models import User
from django_celery_beat.models import PeriodicTask, IntervalSchedule

def create_superuser(apps, schema_editor):
    if User.objects.filter(username='foo').count() == 0:
        superuser = User.objects.create_superuser(
            username='foo',
            email='foo@foo.com',
            password='foo'
        )
        superuser.save()

def create_period_task(apps, schema_editor):
    schedule, _ = IntervalSchedule.objects.get_or_create(
        every=10,
        period=IntervalSchedule.SECONDS,
    )

    name = 'Update repos'
    if PeriodicTask.objects.filter(name=name).count() == 0:
        PeriodicTask.objects.create(
            interval=schedule,
            name=name,          # simply describes this periodic task.
            task='projects.tasks.update_repo_task',
        )

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_superuser),
        migrations.RunPython(create_period_task),
    ]
