# Generated by Django 4.2 on 2024-08-09 03:58

import os
from django.db import migrations


def _create():
    from django.contrib.auth.models import User

    DJANGO_SU_NAME = os.environ.get('DJANGO_SU_NAME', 'foo')
    DJANGO_SU_EMAIL = os.environ.get('DJANGO_SU_EMAIL', 'foo@foo.com')
    DJANGO_SU_PASSWORD = os.environ.get('DJANGO_SU_PASSWORD', 'foo')

    if User.objects.filter(username=DJANGO_SU_NAME).count() > 0:
        print(f'user {DJANGO_SU_NAME} already created')
        return

    superuser = User.objects.create_superuser(
        username=DJANGO_SU_NAME,
        email=DJANGO_SU_EMAIL,
        password=DJANGO_SU_PASSWORD)

    superuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    def generate_superuser(apps, schema_editor):
        from django.conf import settings

        try:
            if settings.DEV_MODE:
                _create()
        except:
            return

    operations = [
        migrations.RunPython(generate_superuser),
    ]
