# Generated by Django 4.2 on 2024-08-19 04:03

from django.db import migrations

def populate_corrected_fields(apps, schema_editor):
    ProjectActivity = apps.get_model('projects', 'ProjectActivity')
    for activity in ProjectActivity.objects.all():
        activity.corrected_insertions = activity.insertions
        activity.corrected_deletions = activity.deletions
        activity.save()

class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0007_projectactiviy_corrected_deletions_and_more'),  # Replace with the previous migration file
    ]

    operations = [
        migrations.RunPython(populate_corrected_fields),
    ]
