# Generated by Django 4.2 on 2024-05-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_last_stat_commit', models.CharField(default=None, max_length=50, null=True)),
                ('commits_count', models.IntegerField(default=0)),
                ('active_days_count', models.IntegerField(default=0)),
                ('files_count', models.IntegerField(default=0)),
                ('first_commit_id', models.CharField(max_length=50)),
                ('last_commit_id', models.CharField(max_length=50)),
                ('first_commit_date', models.DateTimeField()),
                ('last_commit_date', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_recent_weekly_activity', models.CharField(default='[]', max_length=4096)),
                ('_month_in_year_activity', models.CharField(default='{}', max_length=4096)),
                ('_weekday_activity', models.CharField(default='{}', max_length=4096)),
                ('_hourly_activity', models.CharField(default='{}', max_length=4096)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
