# Generated by Django 4.2 on 2024-06-18 02:14

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_files_count', models.IntegerField(default=0)),
                ('total_lines_count', models.IntegerField(default=0)),
                ('_file_summary', models.TextField(default='[]')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_activity', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('monthly_activity', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('yearly_activity', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
