# Generated by Django 4.2 on 2024-06-05 03:46

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commits_count', models.IntegerField(default=0)),
                ('active_days_count', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('files_count', models.IntegerField(default=0)),
                ('first_commit_id', models.CharField(max_length=50)),
                ('last_commit_id', models.CharField(max_length=50)),
                ('first_commit_at', models.DateTimeField()),
                ('last_commit_at', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_files_count', models.IntegerField(default=0)),
                ('total_lines_count', models.IntegerField(default=0)),
                ('_file_summary', models.TextField(default='[]')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_email', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50)),
                ('commit_count', models.IntegerField(default=0)),
                ('first_commit_date', models.DateTimeField()),
                ('last_commit_date', models.DateTimeField()),
                ('contributed_days', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_activity', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('monthly_activity', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('yearly_activity', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
