# Generated by Django 4.2 on 2024-05-21 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaldata',
            old_name='_last_stat_commit',
            new_name='last_stat_commit',
        ),
    ]
