# Generated by Django 4.2 on 2024-05-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaldata',
            old_name='first_commit_date',
            new_name='first_commit_at',
        ),
        migrations.RenameField(
            model_name='generaldata',
            old_name='last_commit_date',
            new_name='last_commit_at',
        ),
    ]
