# Generated by Django 4.2 on 2024-06-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authordata',
            name='active_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
