# Generated by Django 4.2 on 2024-06-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_authordata_active_days'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralData',
        ),
    ]
