# Generated by Django 4.2 on 2024-05-21 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('stats', '0002_rename__last_stat_commit_generaldata_last_stat_commit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_top_authors_statistics', models.CharField(default='[]', max_length=4096)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
