# Generated by Django 4.2 on 2024-05-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_authordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydata',
            name='_hourly_activity',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='activitydata',
            name='_month_in_year_activity',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='activitydata',
            name='_recent_weekly_activity',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='activitydata',
            name='_weekday_activity',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='authordata',
            name='_top_authors_statistics',
            field=models.TextField(default='[]'),
        ),
    ]
