# Generated by Django 4.2 on 2024-05-21 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('stats', '0004_alter_activitydata__hourly_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_files_count', models.IntegerField(default=0)),
                ('total_lines_count', models.IntegerField(default=0)),
                ('_file_summary', models.TextField(default='[]')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
