# Generated by Django 4.2 on 2024-05-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_filedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authordata',
            old_name='_top_authors_statistics',
            new_name='_authors_statistics',
        ),
    ]
