version: "3"

services:
  app:
    container_name: beatsight_dev
    build:
      context: ..
      dockerfile: docker/Dockerfile-dev
    image: beatsight:dev
    # entrypoint: ["tail", "-f", "/dev/null"]
    entrypoint: ["make", "run"]
    environment:
      - PYTHONPATH=/Users/xiez/dev/beatsight/vendor/repostat/:$PYTHONPATH
    volumes:
      - ..:/Users/xiez/dev/beatsight
      - /Users/xiez/src/seahub:/seahub
      - ../../../dev/17zuoye/bank:/bank
      - ../../../dev/17zuoye/ferrum:/ferrum
      - ../../../dev/17zuoye/gemserver:/gemserver
      - ../../../dev/17zuoye/question-bank:/question-bank
      - ../../../dev/17zuoye/aquarius:/aquarius
    ports:
      - "8081:8081"
    networks:
      - beatsight-main

  web:
    container_name: beatsight_web_dev
    build:
      context: ..
      dockerfile: docker/web-Dockerfile-dev
    image: beatsight-web:dev
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - ../web:/web
    ports:
      - "4200:4200"
    networks:
      - beatsight-main

networks:
  beatsight-main:
    driver: bridge      
      