version: "3"

x-healthcheck-defaults: &healthcheck_defaults
  # Avoid setting the interval too small, as docker uses much more CPU than one would expect.
  # Related issues:
  # https://github.com/moby/moby/issues/39102
  # https://github.com/moby/moby/issues/39388
  interval: 30s
  timeout: 30s
  retries: 10
  start_period: 10s

services:
  core:
    container_name: beatsight_core
    image: beatsight-core
    ports:
      - "50052:50051"
    networks:
      - beatsight-main
    volumes:
      - ../../beatsight-core/core.conf:/core.conf
      - ../../beatsight-core/license.json:/license.json

  app:
    container_name: ${APP_NAME:-beatsight_dev}
    build:
      context: ..
      dockerfile: docker/Dockerfile-dev
    image: beatsight:dev
    entrypoint: ["tail", "-f", "/dev/null"]
    # entrypoint: ["make", "run"]
    environment:
      - PYTHONPATH=/Users/xiez/dev/beatsight/vendor/repostat/:$PYTHONPATH
    volumes:
      - repo-data:/beatsight-data
      - ..:/Users/xiez/dev/beatsight
      # - /Users/xiez/dev/beatsight-web:/Users/xiez/dev/beatsight-web
      # - /Users/xiez/dev/SICP-exercises:/sicp
      # - /Users/xiez/dev/beatsight-web:/beatsight-web
      # - /Users/xiez/dev/coreui-free-react-admin-template:/coreui-free-react-admin-template
      # - ../../../dev/17zuoye/bank:/bank
      # - ../../../dev/17zuoye/ferrum:/ferrum
      # - ../../../dev/17zuoye/gemserver:/gemserver
      # - ../../../dev/17zuoye/question-bank:/question-bank
      # - ../../../dev/17zuoye/aquarius:/aquarius
    ports:
      - "8081:8081"
    networks:
      - beatsight-main
    depends_on:
      - core
      - redis
      - rabbitmq
      - postgres
      # - celery
      # - beat

  # web:
  #   container_name: beatsight_web_dev
  #   build:
  #     context: ..
  #     dockerfile: docker/web-Dockerfile-dev
  #   image: beatsight-web:dev
  #   entrypoint: ["tail", "-f", "/dev/null"]
  #   volumes:
  #     - ../web:/web
  #   ports:
  #     - "4200:4200"
  #   networks:
  #     - beatsight-main

  postgres:
    container_name: beatsight-postgres
    # Using the same postgres version as Sentry dev for consistency purposes
    image: "postgres:14.13"
    healthcheck:
      <<: *healthcheck_defaults
      # Using default user "postgres" from sentry/sentry.conf.example.py or value of POSTGRES_USER if provided
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
    command:
      [
        "postgres",
        "-c",
        "max_connections=${POSTGRES_MAX_CONNECTIONS:-100}",
      ]
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - "beatsight-postgres:/var/lib/postgresql/data"
    networks:
      - beatsight-main
  
  rabbitmq:
    container_name: beatsight-mq
    image: rabbitmq:3-management-alpine
    healthcheck:
      <<: *healthcheck_defaults
      test: rabbitmq-diagnostics -q ping
    ports:
        # - 5672:5672
        - 15672:15672
    volumes:
        - beatsight-mq:/var/lib/rabbitmq
        - beatsight-mq-log:/var/log/rabbitmq
    networks:
      - beatsight-main

  redis:
    container_name: beatsight-reids
    image: redis:alpine
    healthcheck:
      <<: *healthcheck_defaults
      test: redis-cli ping
    volumes:
      - redis-data:/data
    networks:
      - beatsight-main

  celery:
    # build: .
    # user: django-user
    container_name: beatsight_celery
    image: beatsight:dev
    environment:
      - PYTHONPATH=/Users/xiez/dev/beatsight/vendor/repostat/:$PYTHONPATH
    # command: ["python", "-m", "celery", "-A", "beatsight", "worker", "--loglevel=info"]
    command: ["python", "manage.py", "celery"]
    volumes:
      - repo-data:/beatsight-data
      - ..:/Users/xiez/dev/beatsight
    depends_on:
      - redis
    networks:
      - beatsight-main

  beat:
    image: beatsight:dev
    environment:
      - PYTHONPATH=/Users/xiez/dev/beatsight/vendor/repostat/:$PYTHONPATH
    command: ["python", "-m", "celery", "-A", "beatsight", "beat", "--loglevel=info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
    volumes:
      - repo-data:/beatsight-data
      - ..:/Users/xiez/dev/beatsight
    depends_on:
      - redis
    networks:
      - beatsight-main

networks:
  beatsight-main:
    driver: bridge      

volumes:
  repo-data:
  redis-data:
  beatsight-mq:
  beatsight-postgres:
  # These store ephemeral data that needn't persist across restarts.
  # That said, volumes will be persisted across restarts until they are deleted.
  beatsight-mq-log:
