version: "3"

services:
  core:
    container_name: beatsight_core
    image: beatsight-core
    ports:
      - "50052:50051"
    networks:
      - beatsight-main
    volumes:
      - /Users/xiez/dev/beatsight-core/core.conf:/core.conf
      - /Users/xiez/dev/beatsight-lic/license_combined.json:/license.json

  app:
    container_name: beatsight_dev
    build:
      context: ..
      dockerfile: docker/Dockerfile-dev
    image: beatsight:dev
    entrypoint: ["tail", "-f", "/dev/null"]
    # entrypoint: ["make", "run"]
    environment:
      - PYTHONPATH=/Users/xiez/dev/beatsight/vendor/repostat/:$PYTHONPATH
    volumes:
      - repo-data:/beatsight-data
      - ..:/Users/xiez/dev/beatsight
      # - /Users/xiez/src/seahub:/seahub
      # - /Users/xiez/dev/SICP-exercises:/sicp
      # - /Users/xiez/dev/beatsight-web:/beatsight-web
      # - /Users/xiez/dev/coreui-free-react-admin-template:/coreui-free-react-admin-template
      # - ../../../dev/17zuoye/bank:/bank
      # - ../../../dev/17zuoye/ferrum:/ferrum
      # - ../../../dev/17zuoye/gemserver:/gemserver
      # - ../../../dev/17zuoye/question-bank:/question-bank
      # - ../../../dev/17zuoye/aquarius:/aquarius
    ports:
      - "8081:8081"
    networks:
      - beatsight-main
    depends_on:
      - core
      - redis
      # - celery
      # - beat

  # web:
  #   container_name: beatsight_web_dev
  #   build:
  #     context: ..
  #     dockerfile: docker/web-Dockerfile-dev
  #   image: beatsight-web:dev
  #   entrypoint: ["tail", "-f", "/dev/null"]
  #   volumes:
  #     - ../web:/web
  #   ports:
  #     - "4200:4200"
  #   networks:
  #     - beatsight-main

  redis:
    container_name: beatsight-reids
    image: redis:alpine
    volumes:
      - redis-data:/data
    networks:
      - beatsight-main

  celery:
    # build: .
    # user: django-user
    container_name: beatsight_celery
    image: beatsight:dev
    environment:
      - PYTHONPATH=/Users/xiez/dev/beatsight/vendor/repostat/:$PYTHONPATH
    # command: ["python", "-m", "celery", "-A", "beatsight", "worker", "--loglevel=info"]
    command: ["python", "manage.py", "celery"]
    volumes:
      - repo-data:/beatsight-data
      - ..:/Users/xiez/dev/beatsight
    depends_on:
      - redis
    networks:
      - beatsight-main

  beat:
    image: beatsight:dev
    environment:
      - PYTHONPATH=/Users/xiez/dev/beatsight/vendor/repostat/:$PYTHONPATH
    command: ["python", "-m", "celery", "-A", "beatsight", "beat", "--loglevel=info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
    volumes:
      - repo-data:/beatsight-data
      - ..:/Users/xiez/dev/beatsight
    depends_on:
      - redis
    networks:
      - beatsight-main

networks:
  beatsight-main:
    driver: bridge      

volumes:
  repo-data:
  redis-data: