"""
This file is part of Beatsight.

Copyright (C) 2024-2025 Beatsight Ltd.
Licensed under the GNU General Public License v3.0.
"""

PL_EXT = {
    'asax': 'ASP',
    'asm': 'Assembly',
    'asp': 'ASP',
    'aspx': 'ASPX',
    'awk': 'Awk',
    'bash': 'Bash',
    'cbl': 'COBOL',
    'cmake': 'CMake',
    'cob': 'COBOL',
    'css': 'CSS',
    'c': 'C',
    'cpp': 'C++',
    'cc': 'C++',
    'dart': 'Dart',
    'dockerfile': 'Dockerfile',
    'erl': 'Erlang',
    'es': 'JavaScript',
    'es6': 'JavaScript',
    'ex': 'Elixir',
    'exs': 'Elixir',
    'f': 'Fortran',
    'f90': 'Fortran',
    'f95': 'Fortran',
    'go': 'Go',
    'groovy': 'Groovy',
    'gvy': 'Groovy',
    'h': 'C',
    'hrl': 'Erlang',
    'hs': 'Haskell',
    'htm': 'HTM',
    'html': 'HTML',
    'java': 'Java',
    'jl': 'Julia',
    'js': 'JavaScript',
    'jsx': 'JavaScript',
    'jsp': 'JSP',
    'jspx': 'JSTL',
    'kt': 'Kotlin',
    'kts': 'Kotlin',
    'l': 'Lisp',
    'less': 'Less',
    'lhs': 'Haskell',
    'lisp': 'Lisp',
    'lsp': 'Lisp',
    'lua': 'Lua',
    'm': 'MATLAB',
    'make': 'Makefile',
    'makefile': 'Makefile',
    'ml': 'OCaml',
    'mli': 'OCaml',
    'nawk': 'Awk',
    'pas': 'Delphi',
    'php': 'PHP',
    'pl': 'Prolog',
    'pm': 'Perl',
    'pro': 'Prolog',
    'ps1': 'PowerShell',
    'psm1': 'PowerShell',
    'py': 'Python',
    'pyx': 'Python',
    'r': 'R',
    'rb': 'Ruby',
    'rdata': 'R',
    'rkt': 'Racket',
    'rs': 'Rust',
    's': 'Assembly',
    'sass': 'SASS',
    'scala': 'Scala',
    'scm': 'Scheme',
    'scss': 'SCSS',
    'sh': 'Shell',
    'sql': 'SQL',
    'ss': 'Scheme',
    'swift': 'Swift',
    'tcl': 'Tcl',
    'ts': 'TypeScript',
    'tsx': 'TypeScript',
    'vb': 'VB',
    'vbs': 'VBScript',
    'zsh': 'Zsh'
}
