# Generated by Django 4.2 on 2024-05-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(max_length=10)),
                ('first_commit_at', models.DateTimeField()),
                ('last_commit_at', models.DateTimeField()),
                ('contributed_days', models.IntegerField()),
            ],
        ),
    ]
