# Generated by Django 4.2 on 2024-07-05 10:09

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃')], default='inactive', max_length=10)),
                ('first_commit_at', models.DateTimeField()),
                ('last_commit_at', models.DateTimeField()),
                ('contributed_days', models.IntegerField(default=0)),
                ('active_days', models.IntegerField(default=0)),
                ('active_days_ratio', models.FloatField(default=0)),
                ('total_commits', models.IntegerField(default=0)),
                ('total_insertions', models.IntegerField(default=0)),
                ('total_deletions', models.IntegerField(default=0)),
                ('total_projects', models.IntegerField(default=0)),
                ('rank_level', models.CharField(default='-', max_length=10)),
                ('rank_percentile', models.FloatField(default=0.0)),
                ('projects', models.ManyToManyField(to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeveloperActivity',
            fields=[
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('developer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='developers.developer')),
                ('daily_activity', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('weekly_activity', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeveloperLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('use_count', models.IntegerField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.developer')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeveloperContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('daily_contribution', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('commits_count', models.IntegerField(default=0)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.developer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
