# Generated by Django 4.2 on 2024-06-05 03:46

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(max_length=10)),
                ('first_commit_at', models.DateTimeField()),
                ('last_commit_at', models.DateTimeField()),
                ('total_commits', models.IntegerField()),
                ('contributed_days', models.IntegerField()),
                ('daily_activity', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('weekly_activity', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('projects', models.ManyToManyField(to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeveloperLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('use_count', models.IntegerField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.developer')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeveloperContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('daily_contribution', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.developer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
