# Generated by Django 4.2 on 2024-06-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='status',
            field=models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃')], default='inactive', max_length=10),
        ),
    ]
