# Generated by Django 4.2 on 2024-06-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='total_projects',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
