# Generated by Django 4.2 on 2024-09-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='last_commit_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='developer',
            name='rank_percentile',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='developer',
            name='status',
            field=models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃')], db_index=True, default='inactive', max_length=10),
        ),
        migrations.AlterField(
            model_name='developer',
            name='total_projects',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
