# Generated by Django 4.2 on 2024-05-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_name'),
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='projects',
            field=models.ManyToManyField(to='projects.project'),
        ),
    ]
