# Generated by Django 4.2 on 2024-06-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_developer_total_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='rank_level',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='rank_percentile',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
