# Generated by Django 4.2 on 2024-06-05 08:48

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_developer_rank_level_developer_rank_percentile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperActivity',
            fields=[
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('developer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='developers.developer')),
                ('daily_activity', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('weekly_activity', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='developer',
            name='daily_activity',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='weekly_activity',
        ),
    ]
