# Generated by Django 4.2 on 2024-06-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_language_developer_created_at_developer_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='total_commits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
