# Generated by Django 4.2 on 2024-06-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0004_developeractivity_remove_developer_daily_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='total_deletions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='developer',
            name='total_insertions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='developer',
            name='contributed_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='developer',
            name='rank_level',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='developer',
            name='rank_percentile',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='developer',
            name='total_commits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='developer',
            name='total_projects',
            field=models.IntegerField(default=0),
        ),
    ]
