# Generated by Django 4.2 on 2024-06-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0005_developer_total_deletions_developer_total_insertions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='active_days',
            field=models.IntegerField(default=0),
        ),
    ]
