# Generated by Django 4.2 on 2024-06-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0006_developer_active_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='active_days_ratio',
            field=models.FloatField(default=0),
        ),
    ]
