# Generated by Django 4.2 on 2024-06-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0007_developer_active_days_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='developercontribution',
            name='commits_count',
            field=models.IntegerField(default=0),
        ),
    ]
